### PR TITLE
Micro Reddit clone

### PR DESCRIPTION
**Pull request by BrianSammit**
This pull request contains the project of the micro Reddit clone that have the users, post, and comment models.
In this project, you can create a new user, made a post, and comment on it.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] Post should have many comments.
##### Post
* `has_many :comments`([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @BrianSammit and @alejandrotoledoweb, Great job! 👏  
Both of you have done well on this project.
Let's make a few changes, and we will be done.

- [x] Always try to stick to the project requirements naming conventions as requested in the [project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails): 
Screen Shot 2020-11-14 at 2 50 57 AM. It makes it easier for us to test your code with predefined test.

- [x] A post should have `has_many :comments` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/post_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

- [x] Add User validations to allow a user with a valid username(nickname) and email, that is, it **must be unique**, can't have multiple users with the same username and email

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by kitpao — CHANGES_REQUESTED** [review]
# 👋 Hello @BrianSammit and @alejandrotoledoweb 

Well done adding the relation that a post should have many comments and the user validations 🌟 
**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

You are only missing some details marked in this part:
image

- [x] **MANDATORY** Please add a field for a password in your user with its validations (6-16 char, presence)
- [x] **OPTIONAL** Name is not required, you can delete it if you want

That would be it

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
